// ::: Code Generated by Copilot [5728d601-8dd4-4305-bd51-3109b120768d]. This comment will be removed automatically after the file is saved :::
import React from "react";
import { motion } from "framer-motion";
import { SectionWrapper } from "../../hoc";
import { campusOrganizations } from "../../constants";
import { fadeIn, textVariant } from "../../utils/motion";
import adg from "../../images/adg.jpg";
import "./Campus.css";

const Campus = () => {
  const getClubImage = (imageKey) => {
    if (imageKey === "adg") {
      return <img src={adg} alt="Apple Developers Group VIT" />;
    }

    return <span>{imageKey.toUpperCase()}</span>;
  };

  return (
    <section className="campus" id="Campus">
      <motion.div variants={textVariant()}>
        <p className="AboutH2">Campus leadership</p>
        <h2 className="AboutH1">Clubs and Chapters.</h2>
      </motion.div>

      <motion.p variants={fadeIn("", "", 0.1, 1)} className="AboutP">
        Campus communities where I built web projects, ran onboarding sessions, supported events, and collaborated across domains at VIT Vellore.
      </motion.p>

      <div className="campusGrid">
        {campusOrganizations.map((organization, index) => (
          <motion.article
            className="campusCard"
            variants={fadeIn("up", "spring", index * 0.12, 0.75)}
            key={organization.id}
          >
            <div className="campusMedia">{getClubImage(organization.imageKey)}</div>
            <div className="campusContent">
              <span className="campusDate">{organization.date}</span>
              <h3>{organization.title}</h3>
              <h4>{organization.role}</h4>
              <p>{organization.location}</p>
              <ul>
                {organization.details.map((detail) => (
                  <li key={detail}>{detail}</li>
                ))}
              </ul>
              {organization.buttonUrl && (
                <a href={organization.buttonUrl} target="_blank" rel="noreferrer" className="campusLink">
                  {organization.buttonText}
                </a>
              )}
            </div>
          </motion.article>
        ))}
      </div>
    </section>
  );
};

export default SectionWrapper(Campus, "campus");