// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
import about2 from "../images/about02.gif";
import about3 from "../images/about03.gif";
import about4 from  "../images/about04.gif";

import icon8 from "../images/icons_sql_light.svg";
import icon9 from "../images/icons_github_light.svg";
import icon10 from "../images/icons_git_light.svg";
import icon3 from "../images/icons_js_light.svg";
import icon12 from "../images/icons_python_light.svg";
import icon17 from "../images/icons_sap.png";

import projectImage1 from "../images/projects_adg_recruitment.png";
import projectImage6 from "../images/projects_dv.png";
import projectImage8 from "../images/projects_ch_ext.png";
// ::: Code Generated by Copilot [ca72b9b0-cab8-4768-a6e5-1798a50656df]. This comment will be removed automatically after the file is saved :::
import projectImage9 from "../images/projects_utility.png";
import projectImage10 from "../images/projects_ism.png";  
import projectImage11 from "../images/projects_nlp.png"
import projectImage12 from "../images/projects_portfolio.png"
import projectImage13 from "../images/projects_micro.png"
import walmartInternalImage from "../images/walmart.png";

// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
const projects = [
  {
    // ::: Code Generated by Copilot [da2b4f4e-022e-4a91-97c4-13d313939854]. This comment will be removed automatically after the file is saved :::
    src: walmartInternalImage,
    title: "Cloud Storage Archival Framework",
    subtitle: "104 TB archived with measurable cloud savings",
    info: "Google Cloud Storage | Storage Transfer Service | BigQuery | Python",
    // ::: Code Generated by Copilot [ef1d33c2-0bb7-4644-a13d-c2bc0ac580b2]. This comment will be removed automatically after the file is saved :::
    desc:"Owned archival of 13+ month CILL production data into a dedicated GCS archival bucket, reducing BigQuery and access costs by roughly $45,000 per year while coordinating approvals, rollout, and RCA."
  },
  {
    // ::: Code Generated by Copilot [ca72b9b0-cab8-4768-a6e5-1798a50656df]. This comment will be removed automatically after the file is saved :::
    src:walmartInternalImage,
    title: "Audit Event Listener Enhancement",
    subtitle: "Near real-time financial event triggering",
    info: "REST APIs | Parallel Processing | Kafka | Integration Testing",
    desc:"Improved Audit Event Listener processing for large queue backlogs, cutting average trigger latency by 2-3 seconds per event and reducing 1,000-message backlog processing by about 3 hours."
  },
  {
    src:walmartInternalImage,
    title: "TwinAI - Passive Knowledge Digital Twin",
    subtitle: "Walmart hackathon knowledge assistant",
    info: "LLM | RAG | ChromaDB | Passive Event Capture | Knowledge Graphs",
    desc:"Designed a passive associate knowledge twin concept that captures IDE, terminal, browser, meeting, and LLM activity into hierarchical, queryable knowledge bases with privacy guardrails."
  },
  {
    src:walmartInternalImage,
    title: "CodeSage AI",
    subtitle: "LLM-powered organization wiki generation",
    info: "LLM | RAG | NetworkX | ChromaDB | Entity Linkage",
    desc:"Built a multi-stage wiki pipeline that ingests raw documents, indexes them, and synthesizes cross-document concept pages to reduce hallucination risk for org-specific questions."
  },
  {
    src:projectImage6,
    title: "Space Exploration",
    subtitle: "Unravelling The Secrets Of Dark Matter",
    info: "#DataScience #R #Visualization",
    link:"https://github.com/ANIRUDH-VADERA/Space_Exploration",
    desc:"A visualization dashboard project for exploring space and dark matter datasets."
  },
  {
    src:projectImage8,
    title: "Web Assist Chrome Extension",
    subtitle: "Browser assistant for complex websites",
    info: "JavaScript | Chrome Extension API | CSS | Background Network Handling",
    link:"https://github.com/ANIRUDH-VADERA/WEB_ASSIST",
    desc:"Built a Chrome extension for navigating complex websites and inspecting page content properties."
  },
  {
    src:projectImage10,
    title: "Chat App with Steganography",
    subtitle: "Secure your chats with steganography techniques",
    info: "#ChatApp #Steganography #Node",
    link:"https://github.com/ANIRUDH-VADERA/ISM_Project",
    desc:"Built a chat app concept where messages can be encoded inside images and viewed only by authorized users."
  },
  {
    src:projectImage11,
    title: "Relevant Document Retrieval",
    subtitle: "Finding the right document from a large corpus",
    info: "#NLP #DocumentRetrieval #BM25",
    link:"https://github.com/ANIRUDH-VADERA/RELEVANT-DOCUMENT-RETRIEVAL",
    desc:"Built an NLP-based retrieval project to identify relevant documents from a large collection of files."
  },
  {
    src:projectImage13,
    title: "MINECO - Mine Gas Safety System",
    subtitle: "IoT prototype for hazardous gas detection",
    info: "ESP32 | Arduino | C++ | MQ135 | DHT11",
    link:"https://github.com/ANIRUDH-VADERA/MINECO",
    desc:"Built an IoT safety prototype that detects gas releases and temperature changes in mine environments using ESP32-connected sensors."
  },
  {
    src:projectImage12,
    title: "Portfolio",
    subtitle: "Interactive personal portfolio",
    info: "#React #ThreeJS",
    link:"https://anirudh-vadera.github.io/Portfolio2023-24/",
    desc:"The React and Three.js portfolio you are browsing, built as an interactive presentation of my work and background."
  },
  {
    src:projectImage1,
    title: "ADG Recruitment Platform",
    subtitle: "Internal platform for Apple Developers Group VIT",
    info: "React | Node.js | MongoDB | Express",
    link:"https://github.com/ANIRUDH-VADERA/Recruitment_Portal_ADG",
    desc:"Contributed to a recruitment web app for ADG VIT and helped deliver club web projects including the official website and link tree."
  },
  {
    src:projectImage9,
    title: "Utility Package",
    subtitle: "A collection of smaller apps and backend utilities",
    info: "#BackendProjects #UtilityApps",
    link:"https://transcendent-squirrel-e70c0d.netlify.app",
    desc:"A collection of additional utility projects and experiments built across web and backend workflows."
  },
];


// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
  const services = [
    {
      title: "Distributed Systems Engineer",
      icon: about3,
      desc: "I build event-driven finance systems, microservices, and data pipelines that process high-volume business transactions reliably.",
      link : "https://github.com/ANIRUDH-VADERA"
    },
    {
      title: "Cloud Data Platform Builder",
      icon: about2,
      desc : "I work hands-on with GCP, BigQuery, Cloud Storage, Spark, Kafka, PostgreSQL, Airflow, Kubernetes, and ArgoCD.",
      link : "https://tech.walmart.com/content/walmart-global-tech/en_us.html"
    },
    {
      title: "Competitive Programmer",
      icon: about4,
      desc : "LeetCode Knight, top 5% globally, with 1000+ solved problems and a 1981 peak rating.",
      link : "https://leetcode.com/u/anirudh00711/"
    },
  ];

// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
const impactHighlights = [
  { value: "85%", label: "Walmart revenue journaled through CILL components" },
  { value: "104 TB", label: "production cloud data archived from GCS" },
  { value: "$45K", label: "annual cloud savings delivered" },
  { value: "50%", label: "reduction in production failures through Litmus coverage" },
];

const achievementHighlights = [
  "Making a Difference Award at Walmart Global Tech for FY 2025.",
  "Finalist in Walmart FDF AI Hackathon for an LLM-powered org wiki generation pipeline.",
  "LeetCode Knight, top 5% globally, 1000+ problems solved, peak rating 1981.",
  "Merit Scholarship recipient at VIT Vellore for 2020-2021 and 2021-2022.",
  "Program Representative for CSE CORE at VIT for 2021-2022 and 2022-2023.",
];

const certifications = [
  "Generative AI Architectures with LLMs, Prompt Engineering, RAG, and Vector Databases",
  "Big Data Analysis with Scala and Spark",
  "Functional Programming Principles in Scala",
  "Functional Program Design in Scala",
  "Parallel Programming",
  "Functional Programming in Scala Capstone",
  "The Complete Web Development Bootcamp 2023",
];
  
// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
  const technologies = [
    {
        name: "Scala",
        category: "Backend",
        short: "Sc",
    },
    {
        name: "Python",
        category: "Data Engineering",
        bgColor :"",
        icon: icon12
    },
    // ::: Code Generated by Copilot [ef1d33c2-0bb7-4644-a13d-c2bc0ac580b2]. This comment will be removed automatically after the file is saved :::
    {
      name: "SQL",
      category: "Data",
      short: "SQL",
    },
    {
        name: "Apache Spark",
        category: "Big Data",
        short: "Sp",
    },
    {
        name: "Spark Streaming",
        category: "Streaming",
        short: "SS",
    },
    {
        name: "Kafka",
        category: "Event Streaming",
        short: "Kf",
    },
    {
      name: "KCaaS",
      category: "Kafka Platform",
      short: "KC",
    },
    {
        name: "Google Cloud Platform",
        category: "Cloud",
        short: "GCP",
    },
    {
        name: "BigQuery",
        category: "Analytics",
        short: "BQ",
    },
    {
        name: "Cloud Storage",
        category: "Cloud Data",
        short: "GCS",
    },
    {
      name: "Pub/Sub",
      category: "Messaging",
      short: "PS",
    },
    {
      name: "Data Movement Services",
      category: "Cloud Data",
      short: "DMS",
    },
    {
      name: "Scheduled Queries",
      category: "BigQuery",
      short: "SQ",
    },
    {
      name: "AutoClass",
      category: "Cloud Storage",
      short: "AC",
    },
    {
      name: "PostgreSQL",
      category: "Databases",
      bgColor :"",
      icon: icon8
    },
    {
      name: "MySQL",
      category: "Databases",
      short: "My",
    },
    {
      name: "Flyway",
      category: "Database Migrations",
      short: "Fly",
    },
    {
      name: "Kubernetes",
      category: "Infrastructure",
      short: "K8s",
    },
    {
      name: "ArgoCD",
      category: "Delivery",
      short: "Argo",
    },
    {
      name: "Airflow",
      category: "Orchestration",
      short: "Air",
    },
    {
      name: "REST APIs",
      category: "Backend",
      short: "API",
    },
    {
      name: "API Management",
      category: "Backend",
      short: "APM",
    },
    {
      name: "Microservices",
      category: "Backend",
      short: "MS",
    },
    {
      name: "Distributed Systems",
      category: "Architecture",
      short: "DS",
    },
    {
      name: "Event-Driven Architecture",
      category: "Architecture",
      short: "EDA",
    },
    {
      name: "ETL Pipelines",
      category: "Data Modeling",
      short: "ETL",
    },
    // ::: Code Generated by Copilot [b552ff9b-07e9-411e-8078-7f5250925931]. This comment will be removed automatically after the file is saved :::
    {
      name: "Data Modeling",
      category: "Data Engineering",
      short: "DM",
    },
    {
      name: "PySpark",
      category: "Data Engineering",
      short: "PyS",
    },
    {
      name: "Storage Transfer Service",
      category: "Cloud Data",
      short: "STS",
    },
    {
      name: "Cloud Cost Optimization",
      category: "Cloud FinOps",
      short: "CCO",
    },
    {
      name: "Financial Reconciliation",
      category: "Finance Tech",
      short: "Recon",
    },
    {
      name: "SAP Acknowledgements",
      category: "Finance Tech",
      short: "Ack",
    },
    {
      name: "LLM / RAG",
      category: "AI Systems",
      short: "AI",
    },
    {
      name: "Vector DB",
      category: "AI Systems",
      short: "VDB",
    },
    {
      name: "Graph DB",
      category: "AI Systems",
      short: "GDB",
    },
    {
      name: "ZIO",
      category: "Scala",
      short: "ZIO",
    },
    {
      name: "Akka",
      category: "Scala",
      short: "Ak",
    },
    {
      name: "Apache Camel",
      category: "Integration",
      short: "Cam",
    },
    {
      name: "JavaScript",
      category: "Web",
      bgColor :"",
      icon: icon3
    },
    {
      name: "SAP ABAP",
      category: "Finance Tech",
      bgColor :"",
      icon: icon17
    },
    {
      name: "SAP",
      category: "Finance Tech",
      short: "SAP",
    },
    {
      name: "Chrome Extensions",
      category: "Web",
      short: "CE",
    },
    {
      name: "ScalaTest",
      category: "Testing",
      short: "ST",
    },
    {
      name: "Mockito",
      category: "Testing",
      short: "Mo",
    },
    {
      name: "Integration Testing",
      category: "Testing",
      short: "IT",
    },
    {
      name: "CI/CD",
      category: "Delivery",
      short: "CI",
    },
    {
      name: "GitHub",
      category: "Developer Tools",
      bgColor :"",
      icon: icon9
    },
    {
      name: "Git",
      category: "Developer Tools",
      bgColor :"",
      icon: icon10
    },
]  

// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
let experience = [
  {
    id: 1,
    title: "Walmart Global Tech | Software Engineer III | Finance Technology - CILL",
    location: "Chennai, Tamil Nadu, India",
    details: [
      // ::: Code Generated by Copilot [ef1d33c2-0bb7-4644-a13d-c2bc0ac580b2]. This comment will be removed automatically after the file is saved :::
      "Work on CILL components that journal roughly 85% of Walmart revenue and process high-volume finance transactions every day.",
      "Expanded CILL into MXCAM and LATAM Finance 2.0 across 6 countries and 50+ source systems, supporting markets representing about 10% of Walmart global business.",
      "Implemented currency limitation, document splitting, exchange-rate, and local-currency rules to prevent SAP failures in high-value local-currency journal flows.",
      "Designed local-currency exchange-rate derivation and local-currency calculation rules for LATAM journal processing.",
      "Played a major role in international testing cycles for core CILL processes while moving SAP acknowledgement processing toward near real time, improving execution time by 25%."
    ],
      date: "May 2026 - Present",
    icon: "work",
    school: "walmart",
    buttonText: "View Website",
    buttonUrl: 'https://tech.walmart.com/content/walmart-global-tech/en_us.html',
  },
  {
    id: 2,
    title: "Walmart Global Tech | Software Engineer II | Finance Technology - CILL",
    location: "Chennai, Tamil Nadu, India",
    details: [
      "Owned GCS archival end to end, moving 104 TB of 13+ month data and delivering roughly $45,000 in annual cloud savings.",
      "Built REST APIs and parallel Audit Event Listener processing, cutting trigger latency by 2-3 seconds per event and reducing large queue backlog time by about 3 hours.",
      "Built Ending Inventory reconciliation and backward-acknowledgement flows, shifting processing from batch windows toward near real time.",
      "Developed unified Recon Adapter capabilities that improved failure visibility, reduced manual troubleshooting, and lowered MTTD/MTTR by about 20%.",
      "Implemented 7 lead company code derivation strategies to prevent tax miscalculations and improve finance compliance workflows.",
      "Optimized PySpark DataFrame upserts into PostgreSQL for GLAD, reducing update runtime from about 3 hours to 13 minutes."
    ],
      date: "July 2024 - April 2026",
    icon: "work",
    school: "walmart",
    buttonText: "View Website",
    buttonUrl: 'https://tech.walmart.com/content/walmart-global-tech/en_us.html',
  },
  {
    id: 3,
    title: "Walmart Global Tech | Software Engineering Intern | Finance Technology - CILL",
    location: "Chennai, Tamil Nadu, India",
    details: [
      "Migrated cross-reference storage from MySQL to PostgreSQL, consolidated database connections, rewrote SQL flows, and moved scripts to Flyway.",
      "Extended Litmus integration tests across 128+ CILL repositories and 20+ pre-SAP business rules, reducing production failures by 50% and release cycles by 30%.",
      "Owned config-driven error-log alerting and ServiceNow incident creation, reducing MTTD by 90% and MTTR by 20% during Month End Closure.",
      "Worked on source-to-CILL-to-SAP acknowledgement pipelines used by finance teams to validate journal postings and reconciliation outcomes."
    ],
      date: "January 2024 - June 2024",
    icon: "work",
    school: "walmart",
    buttonText: "View Website",
    buttonUrl: 'https://tech.walmart.com/content/walmart-global-tech/en_us.html',
  },
  {
    id: 4,
    title: "Walmart Global Tech | Software Development Engineer Intern | SAP Accounts Receivable",
    location: "Chennai, Tamil Nadu, India",
    details: [
      "Built an SAP ABAP Bank Account Master File report to fetch GL account details by fiscal year and application number.",
      "Supported functional teams with database-backed reporting that improved finance workflow turnaround and reduced downtime by 10%.",
      "Learned core functional and technical flows across Walmart finance technology systems."
    ],
      date: "May 2023 - July 2023",
    icon: "work",
    school: "walmart",
    buttonText: "View Website",
    buttonUrl: 'https://tech.walmart.com/content/walmart-global-tech/en_us.html',
  }
];

// ::: Code Generated by Copilot [5728d601-8dd4-4305-bd51-3109b120768d]. This comment will be removed automatically after the file is saved :::
let campusOrganizations = [
  {
    id: 1,
    title: "Apple Developers Group VIT",
    role: "Senior Core Member | Web Development",
    location: "Vellore, Tamil Nadu, India",
    date: "December 2020 - April 2024",
    imageKey: "adg",
    // ::: Code Generated by Copilot [1a57d81a-e627-4a58-a6da-4732137e5522]. This comment will be removed automatically after the file is saved :::
    details: [
      "Built recruitment, official website, Link Tree, and CSS generator projects for internal club use.",
      "Conducted React training sessions and helped onboard new members into web development projects.",
      "Collaborated with design, content, and operations domains to deliver club applications and event tooling.",
      "Runner-up in the ADG intra-club hackathon in 2021."
    ]
  },
  {
    id: 2,
    title: "Technology and Gaming Club VIT",
    role: "Core Member | Web Development and Game Management",
    location: "Vellore, Tamil Nadu, India",
    date: "December 2020 - December 2021",
    imageKey: "tag",
    details: [
      "Contributed to GAME-A-THON, the club's flagship event.",
      "Supported the TAG Cypher intra-club gaming tournament and game-management workflows.",
      "Hosted a CS:GO server on AWS for tournament participants."
    ]
  }
];


let timelineElements = [
  {
    // ::: Code Generated by Copilot [ef1d33c2-0bb7-4644-a13d-c2bc0ac580b2]. This comment will be removed automatically after the file is saved :::
    id: 3,
    title: "Vellore Institute Of Technology, Vellore",
    location: "Vellore, Tamil Nadu, India",
    description:
      "Bachelor of Technology in Computer Science and Engineering with a CGPA of 9.54 / 10.",
    buttonText: "View School Website",
    date: "September 2020 - April 2024",
    icon: "work",
    school: "vit",
    buttonUrl: 'https://vit.ac.in/',
    add:"Branch : Computer Science and Engineering (CORE)"
  },
  {
    id: 2,
    title: "Army Public School - (Class XII)",
    location: "Nehru Road, Lucknow, Uttar Pradesh, India",
    description:
      "Completed Class XII with 95.6% in PCM with Computer Science before pursuing engineering in Computer Science.",
    buttonText: "View School Website",
    date: "April 2019 - April 2020",
    icon: "school",
    school: "aps",
    buttonUrl: 'https://www.apsnrlucknow.org/',
    add:"Branch : PCM with Computer Science"
  },
  {
    id: 1,
    title: "Army Public School - (Class X)",
    location: "Nehru Road, Lucknow, Uttar Pradesh, India",
    description:
      "Completed Class X with 92.4%, building the academic base that led into PCM and Computer Science.",
    buttonText: "View School Website",
    date: "April 2017 - April 2018",
    icon: "school",
    school: "aps",
    buttonUrl: 'https://www.apsnrlucknow.org/',
    add:"Branch : PCM with Computer Science"
  }
];


const MenuData = [
      {
          title: "Home",
          url: "Home",
          cName : "nav-links",
          icon : "fa-solid fa-house-user"
      },
      {
          title: "About",
          url: "About",
          cName : "nav-links",
          icon : "fa-solid fa-circle-info"
      },
      {
        title: "Work Experience",
        url: "Experience",
        cName : "nav-links",
        icon : "fa-solid fa-briefcase"
      },
      {
        title: "Skills",
        url: "Skills",
        cName : "nav-links",
        icon : "fa-solid fa-book-atlas"
      },
      {
        title: "Projects",
        url: "Projects",
        cName : "nav-links",
        icon : "fa-solid fa-diagram-project"
      },
      {
          title: "Education",
          url: "Education",
          cName : "nav-links",
          icon : "fa-solid fa-school"
      },
        {
          title: "Campus Clubs",
          url: "Campus",
          cName : "nav-links",
          icon : "fa-solid fa-users"
        },
      {
          title: "Contact",
          url: "Contact",
          cName : "nav-links",
          icon : "fa-solid fa-address-book"
      },
  ];


// ::: Code Generated by Copilot [1fc79dcb-08bc-4b86-81da-7d2a849c2b79]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [5728d601-8dd4-4305-bd51-3109b120768d]. This comment will be removed automatically after the file is saved :::
  export { services,MenuData,timelineElements,technologies,projects,experience,campusOrganizations,impactHighlights,achievementHighlights,certifications };