// ::: Code Generated by Copilot [1cb77a4e-23ac-4941-8bec-14129465d461]. This comment will be removed automatically after the file is saved :::
import React,{useState} from 'react'
import navbarLogo from "../../images/logo-white.png"
import "./Navbar.css"
import { MenuData } from '../../constants'
import {Link} from 'react-router-dom';

function Navbar() {
    const [state,setState] = useState({clicked:false});
  
    const handleClick = ()=>{
        setState((prev)=>{
            return {clicked:!prev.clicked}
    });
    }

    const handleClick2 = (url)=>{
        const element = document.getElementById(url);
        if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
        setState({clicked:false});
        }
      }
      

    // ::: Code Generated by Copilot [1cb77a4e-23ac-4941-8bec-14129465d461]. This comment will be removed automatically after the file is saved :::
    return (
    <nav className="NavbarItems">
        <Link to="/" onClick={()=>{
            window.scrollTo(0,0);
        }} className="navbarMainLink"><h1><img alt="Anirudh Vadera logo" className="navbarLogo" src = {navbarLogo} /><span>Anirudh Vadera</span><small>Software Engineer III</small></h1></Link>
        <div className="menuIcons" onClick={handleClick}>
            <i className={state.clicked ? "fas fa-times": "fas fa-bars"}></i>
        </div>
        <ul className={state.clicked ? "navbarMenu active" : "navbarMenu"}>
            {MenuData.map((item,index)=>{
                return (
                    <li className="navbarList" key={index}><Link onClick={()=>{handleClick2(item.url);}}  className={item.cName}>
                        <i className={item.icon}></i>{item.title}
                    </Link></li>
                )
            })}
            
        </ul>
    </nav>
  )
}

export default Navbar