// ::: Code Generated by Copilot [62264539-a08d-4473-9096-5fedcbb473df]. This comment will be removed automatically after the file is saved :::
export const textVariant = (delay) => {
    return {
      hidden: {
        y: -50,
        opacity: 0,
      },
      show: {
        y: 0,
        opacity: 1,
        transition: {
          type: "spring",
          duration: 1.25,
          delay: delay,
        },
      },
    };
  };
  
  export const fadeIn = (direction, type, delay, duration) => {
    return {
      hidden: {
        // ::: Code Generated by Copilot [62264539-a08d-4473-9096-5fedcbb473df]. This comment will be removed automatically after the file is saved :::
        // ::: Code Generated by Copilot [24d8999f-0e41-4e1b-9415-a15fe5e89793]. This comment will be removed automatically after the file is saved :::
        x: direction === "left" ? 12 : direction === "right" ? -12 : 0,
        y: direction === "up" ? 32 : direction === "down" ? -32 : 0,
        opacity: 0,
      },
      show: {
        x: 0,
        y: 0,
        opacity: 1,
        transition: {
          type: type,
          delay: delay,
          duration: duration,
          ease: "easeOut",
        },
      },
    };
  };
  
  export const zoomIn = (delay, duration) => {
    return {
      hidden: {
        scale: 0,
        opacity: 0,
      },
      show: {
        scale: 1,
        opacity: 1,
        transition: {
          type: "tween",
          delay: delay,
          duration: duration,
          ease: "easeOut",
        },
      },
    };
  };
  
  export const slideIn = (direction, type, delay, duration) => {
    return {
      hidden: {
        // ::: Code Generated by Copilot [62264539-a08d-4473-9096-5fedcbb473df]. This comment will be removed automatically after the file is saved :::
        // ::: Code Generated by Copilot [24d8999f-0e41-4e1b-9415-a15fe5e89793]. This comment will be removed automatically after the file is saved :::
        x: direction === "left" ? -8 : direction === "right" ? 8 : 0,
        y: direction === "up" ? 32 : direction === "down" ? -32 : 0,
      },
      show: {
        x: 0,
        y: 0,
        transition: {
          type: type,
          delay: delay,
          duration: duration,
          ease: "easeOut",
        },
      },
    };
  };
  
  export const staggerContainer = (staggerChildren, delayChildren) => {
    return {
      hidden: {},
      show: {
        transition: {
          staggerChildren: staggerChildren,
          delayChildren: delayChildren || 0,
        },
      },
    };
  };