// ::: Code Generated by Copilot [bd6ecdd4-0652-485d-ad16-7dc8d6b3b39c]. This comment will be removed automatically after the file is saved :::
import React,{useRef} from 'react'
import "./Projects.css";
import { motion } from "framer-motion";

import { projects } from "../../constants";
import {SectionWrapper } from "../../hoc";
import useOnScreen from "../../hooks/useOnScreen";
import cn from "classnames";
import { slideIn } from "../../utils/motion.js";

function GalleryItem({
    src,
    info,
    subtitle,
    title,
    index,
    link,
    desc
  }) {

    const ref = useRef(null);
    const onScreen = useOnScreen(ref, 0.5);


    return (
      <div
      className={cn("gallery-item-wrapper", { "is-reveal": onScreen })}
      ref={ref}
      >
          <div></div>
          <div className={"gallery-item"}>
            <motion.div  
              variants={slideIn("left", "tween", 0.2, 1)}
            className="gallery-item-info">
              <h1 className="gallery-info-title">{title}</h1>
              <h2 className="gallery-info-subtitle">{subtitle}</h2>
              <p className="gallery-info-category">{info}</p>
              <p className="AboutP">{desc}</p>
              {/* ::: Code Generated by Copilot [ef1d33c2-0bb7-4644-a13d-c2bc0ac580b2]. This comment will be removed automatically after the file is saved ::: */}
              {link && <a href={link} target="_blank" rel="noreferrer"><button className="btn1">View project</button></a>}
            </motion.div >
            <div
              className="gallery-item-image"
              style={{ backgroundImage: `url(${src})`}}
            ></div>
          </div>
          <div></div>
        </div>
    );
  }


function Projects() {
    const ref = useRef(null);

  // ::: Code Generated by Copilot [bd6ecdd4-0652-485d-ad16-7dc8d6b3b39c]. This comment will be removed automatically after the file is saved :::
    return (
    <div className='ProjectsPage' id="Projects">
        {/* ::: Code Generated by Copilot [da2b4f4e-022e-4a91-97c4-13d313939854]. This comment will be removed automatically after the file is saved ::: */}
        <div className="ProjectsHeaderPanel">
          {/* ::: Code Generated by Copilot [e8db9e10-4487-4521-8c72-d1f3f324321f]. This comment will be removed automatically after the file is saved ::: */}
          <div>
              <p className='AboutH2'>My work</p>
              <h2 className={`AboutH1`}>Projects.</h2>
          </div>

          <p className='AboutP'>
            Selected production initiatives, hackathon builds, and university projects that show how I approach scale, reliability, applied AI, and practical engineering.
          </p>
        </div>


        

        <div className="gallery projects section-wrapper gallery-wrap" ref={ref}>
              {projects.map((image, index) => (
              <GalleryItem
                  key={index}
                  index={index}
                  {...image}
                  />
              ))}
        </div>

        
    </div>
  )
}

export default SectionWrapper(Projects,"projects");