// ::: Code Generated by Copilot [bd6ecdd4-0652-485d-ad16-7dc8d6b3b39c]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [a2ecaa4a-4552-4f4d-b4d3-14983523bd3b]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [7bc54b24-b385-4937-b103-fe1159756a33]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [a0fb17c5-88de-419f-9652-bc85938ac86c]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [fa7dbbd6-1b2c-473d-922d-db6f12aa258e]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [bff1f83f-79e4-410e-9031-fb920f7e9cc8]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [67750668-c287-48bf-b4bd-97b9e23cf4e9]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [d7f7fb8d-3237-46df-b44d-17918da6286d]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [c31fca73-07ad-497d-b61a-e0717eda8181]. This comment will be removed automatically after the file is saved :::
import React, { useEffect, useMemo, useRef } from 'react'
import * as THREE from "three";
import {SectionWrapper } from "../../hoc";
import {technologies} from "../../constants";
import { motion } from "framer-motion";
import { textVariant } from "../../utils/motion";
import "./Skills.css"

// ::: Code Generated by Copilot [a3f56e72-30c4-4b33-b84f-b3d02dc56fd7]. This comment will be removed automatically after the file is saved :::
const skillLogoSymbols = {
  "Scala": {
    accent: "#dc322f",
    label: "Sc",
    symbol: `<path d="M70 66c42 20 74 18 116 0v28c-42 20-74 20-116 0V66Z" fill="#dc322f"/><path d="M70 112c42 20 74 18 116 0v28c-42 20-74 20-116 0v-28Z" fill="#ef4444"/><path d="M70 158c42 20 74 18 116 0v28c-42 20-74 20-116 0v-28Z" fill="#b91c1c"/>`
  },
  "SQL": {
    accent: "#0ea5e9",
    label: "SQL",
    symbol: `<ellipse cx="128" cy="74" rx="58" ry="24" fill="#38bdf8"/><path d="M70 74v84c0 14 26 25 58 25s58-11 58-25V74" fill="#0ea5e9"/><ellipse cx="128" cy="158" rx="58" ry="25" fill="#0284c7"/><path d="M92 118h72M100 145h56" stroke="#e0f2fe" stroke-width="12" stroke-linecap="round"/>`
  },
  "Apache Spark": {
    accent: "#f97316",
    label: "Sp",
    symbol: `<path d="m128 42 18 54 56-2-46 32 20 54-48-34-48 34 20-54-46-32 56 2 18-54Z" fill="#f97316"/><circle cx="128" cy="126" r="28" fill="#facc15"/><path d="M128 72v108M74 126h108" stroke="#7c2d12" stroke-width="10" stroke-linecap="round" opacity="0.28"/>`
  },
  "Spark Streaming": {
    accent: "#fb923c",
    label: "SS",
    symbol: `<path d="m92 58 24 44 50-11-34 39 26 47-48-20-36 38 5-52-47-23 51-12 9-50Z" fill="#fb923c"/><path d="M138 76c32 12 52 30 66 58M124 112c28 8 46 23 59 46M74 170c26 12 53 15 82 9" fill="none" stroke="#38bdf8" stroke-width="11" stroke-linecap="round"/>`
  },
  "Kafka": {
    accent: "#111827",
    label: "Kf",
    symbol: `<circle cx="128" cy="128" r="24" fill="#111827"/><circle cx="74" cy="82" r="18" fill="#111827"/><circle cx="184" cy="84" r="18" fill="#111827"/><circle cx="184" cy="174" r="18" fill="#111827"/><path d="M92 94 112 116M148 116l24-23M148 140l24 24" stroke="#64748b" stroke-width="12" stroke-linecap="round"/>`
  },
  "KCaaS": {
    accent: "#2563eb",
    label: "KC",
    symbol: `<path d="M72 74h112v108H72z" fill="none" stroke="#2563eb" stroke-width="16"/><path d="M96 158V98M96 128l48-36M112 128l48 36" fill="none" stroke="#60a5fa" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><circle cx="184" cy="74" r="18" fill="#22c55e"/>`
  },
  "Google Cloud Platform": {
    accent: "#4285f4",
    label: "GCP",
    symbol: `<path d="M78 158h100c23 0 40-16 40-37 0-20-15-35-35-38-9-21-29-35-53-35-30 0-54 20-60 48-20 4-34 17-34 34 0 16 17 28 42 28Z" fill="#4285f4"/><path d="M64 154h60" stroke="#34a853" stroke-width="18" stroke-linecap="round"/><path d="M140 60c20 4 35 14 45 31" stroke="#fbbc05" stroke-width="18" stroke-linecap="round"/><path d="M184 88c18 6 30 18 34 35" stroke="#ea4335" stroke-width="18" stroke-linecap="round"/>`
  },
  "BigQuery": {
    accent: "#669df6",
    label: "BQ",
    symbol: `<path d="M128 42 202 84v88l-74 42-74-42V84l74-42Z" fill="#1a73e8"/><rect x="86" y="134" width="18" height="36" rx="5" fill="#bfdbfe"/><rect x="119" y="104" width="18" height="66" rx="5" fill="#bfdbfe"/><rect x="152" y="122" width="18" height="48" rx="5" fill="#bfdbfe"/><circle cx="128" cy="128" r="58" fill="none" stroke="#93c5fd" stroke-width="10"/>`
  },
  "Cloud Storage": {
    accent: "#0ea5e9",
    label: "GCS",
    symbol: `<path d="M72 88h112l18 34v66H54v-66l18-34Z" fill="#38bdf8"/><path d="M82 72h92l10 28H72l10-28Z" fill="#fbbf24"/><path d="M76 134h104M76 164h104" stroke="#075985" stroke-width="12" stroke-linecap="round" opacity="0.38"/>`
  },
  "Pub/Sub": {
    accent: "#a855f7",
    label: "PS",
    symbol: `<circle cx="74" cy="128" r="26" fill="#a855f7"/><circle cx="182" cy="82" r="22" fill="#22d3ee"/><circle cx="182" cy="174" r="22" fill="#34d399"/><path d="M100 120 160 92M100 136l60 28" stroke="#c4b5fd" stroke-width="14" stroke-linecap="round"/><path d="m154 74 30 8-22 22M154 152l30 22-34 7" fill="none" stroke="#f8fafc" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  "Data Movement Services": {
    accent: "#14b8a6",
    label: "DMS",
    symbol: `<ellipse cx="75" cy="76" rx="34" ry="16" fill="#38bdf8"/><path d="M41 76v74c0 9 15 17 34 17s34-8 34-17V76" fill="#0284c7"/><ellipse cx="181" cy="106" rx="34" ry="16" fill="#4ade80"/><path d="M147 106v74c0 9 15 17 34 17s34-8 34-17v-74" fill="#16a34a"/><path d="M110 116h52" stroke="#f59e0b" stroke-width="14" stroke-linecap="round"/><path d="m154 92 28 24-28 24" fill="none" stroke="#f59e0b" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  "Scheduled Queries": {
    accent: "#6366f1",
    label: "SQ",
    symbol: `<circle cx="92" cy="94" r="44" fill="#6366f1"/><path d="M92 68v30l22 14" stroke="#e0e7ff" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/><rect x="92" y="132" width="96" height="58" rx="14" fill="#38bdf8"/><path d="M116 154h48M116 174h30" stroke="#075985" stroke-width="10" stroke-linecap="round"/>`
  },
  "AutoClass": {
    accent: "#f59e0b",
    label: "AC",
    symbol: `<path d="M128 48 196 86v76l-68 46-68-46V86l68-38Z" fill="#f59e0b"/><path d="M88 103h80M88 131h80M88 159h80" stroke="#78350f" stroke-width="12" stroke-linecap="round" opacity="0.42"/><path d="m174 70 22 16-22 16" fill="#fde68a"/>`
  },
  "MySQL": {
    accent: "#00758f",
    label: "My",
    symbol: `<path d="M54 132c24-38 62-54 112-48 20 2 32 12 36 29-24-10-47-10-70 2 20 8 36 22 47 42-43-16-82-11-117 17 3-14 8-28 15-40-8 0-16-1-23-2Z" fill="#00758f"/><path d="M89 162c28-18 57-22 88-12" stroke="#f97316" stroke-width="13" stroke-linecap="round"/>`
  },
  "Flyway": {
    accent: "#cc0200",
    label: "Fly",
    symbol: `<path d="M60 86h96c24 0 42 18 42 42s-18 42-42 42H60" fill="none" stroke="#cc0200" stroke-width="18" stroke-linecap="round"/><path d="m142 102 36 26-36 26" fill="none" stroke="#fca5a5" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><path d="M60 128h118" stroke="#7f1d1d" stroke-width="12" stroke-linecap="round"/>`
  },
  "Kubernetes": {
    accent: "#326ce5",
    label: "K8s",
    symbol: `<path d="M128 42 202 84v88l-74 42-74-42V84l74-42Z" fill="#326ce5"/><circle cx="128" cy="128" r="34" fill="none" stroke="#dbeafe" stroke-width="12"/><path d="M128 72v28M128 156v28M80 100l24 14M152 142l24 14M176 100l-24 14M104 142l-24 14" stroke="#dbeafe" stroke-width="10" stroke-linecap="round"/>`
  },
  "ArgoCD": {
    accent: "#ef7b4d",
    label: "Argo",
    symbol: `<circle cx="128" cy="128" r="62" fill="none" stroke="#ef7b4d" stroke-width="16"/><path d="M128 66c31 0 57 23 62 52" fill="none" stroke="#60a5fa" stroke-width="16" stroke-linecap="round"/><path d="m188 90 10 38-36-14" fill="#60a5fa"/><path d="M96 132h64M128 100v64" stroke="#f8fafc" stroke-width="12" stroke-linecap="round"/>`
  },
  "Airflow": {
    accent: "#017cee",
    label: "Air",
    symbol: `<path d="M128 126 74 68c31-15 64 1 72 36l-18 22Z" fill="#017cee"/><path d="M130 128 188 74c15 31-1 64-36 72l-22-18Z" fill="#00ad46"/><path d="M128 130 182 188c-31 15-64-1-72-36l18-22Z" fill="#fbbc05"/><path d="M126 128 68 182c-15-31 1-64 36-72l22 18Z" fill="#e93e30"/><circle cx="128" cy="128" r="18" fill="#f8fafc"/>`
  },
  "REST APIs": {
    accent: "#22c55e",
    label: "API",
    symbol: `<path d="M86 88 48 128l38 40M170 88l38 40-38 40" fill="none" stroke="#22c55e" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/><path d="m142 78-28 100" stroke="#38bdf8" stroke-width="16" stroke-linecap="round"/><circle cx="128" cy="128" r="14" fill="#f59e0b"/>`
  },
  "API Management": {
    accent: "#8b5cf6",
    label: "APM",
    symbol: `<rect x="58" y="72" width="140" height="112" rx="20" fill="#8b5cf6"/><path d="M84 110h88M84 138h64" stroke="#ede9fe" stroke-width="12" stroke-linecap="round"/><circle cx="184" cy="82" r="20" fill="#22c55e"/><path d="M172 82h24" stroke="#dcfce7" stroke-width="8" stroke-linecap="round"/>`
  },
  "Microservices": {
    accent: "#06b6d4",
    label: "MS",
    symbol: `<rect x="52" y="62" width="54" height="54" rx="14" fill="#06b6d4"/><rect x="150" y="62" width="54" height="54" rx="14" fill="#22c55e"/><rect x="101" y="144" width="54" height="54" rx="14" fill="#f59e0b"/><path d="M106 90h44M88 116l30 28M168 116l-30 28" stroke="#e2e8f0" stroke-width="12" stroke-linecap="round"/>`
  },
  "Distributed Systems": {
    accent: "#64748b",
    label: "DS",
    symbol: `<circle cx="72" cy="82" r="23" fill="#38bdf8"/><circle cx="184" cy="88" r="23" fill="#4ade80"/><circle cx="126" cy="176" r="26" fill="#f59e0b"/><path d="M94 91h68M82 103l32 52M172 106l-34 50" stroke="#94a3b8" stroke-width="12" stroke-linecap="round"/>`
  },
  "Event-Driven Architecture": {
    accent: "#f97316",
    label: "EDA",
    symbol: `<path d="M126 48 78 136h42l-18 72 76-104h-48l24-56h-28Z" fill="#f97316"/><path d="M58 92c22-28 52-44 88-48M198 166c-22 28-52 44-88 48" fill="none" stroke="#38bdf8" stroke-width="12" stroke-linecap="round"/>`
  },
  "ETL Pipelines": {
    accent: "#10b981",
    label: "ETL",
    symbol: `<rect x="42" y="92" width="44" height="72" rx="12" fill="#38bdf8"/><rect x="106" y="92" width="44" height="72" rx="12" fill="#f59e0b"/><rect x="170" y="92" width="44" height="72" rx="12" fill="#10b981"/><path d="M86 128h20M150 128h20" stroke="#f8fafc" stroke-width="12" stroke-linecap="round"/><path d="m100 112 18 16-18 16M164 112l18 16-18 16" fill="none" stroke="#f8fafc" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  // ::: Code Generated by Copilot [4a059fd0-b55c-4ff4-aa67-a88948a791ad]. This comment will be removed automatically after the file is saved :::
  "Data Modeling": {
    accent: "#06b6d4",
    label: "DM",
    symbol: `<rect x="58" y="62" width="58" height="48" rx="12" fill="#38bdf8"/><rect x="140" y="62" width="58" height="48" rx="12" fill="#22c55e"/><rect x="99" y="148" width="58" height="48" rx="12" fill="#f59e0b"/><path d="M87 110v38M169 110v38M116 172h-29M140 172h29" stroke="#e0f2fe" stroke-width="10" stroke-linecap="round"/>`
  },
  "PySpark": {
    accent: "#f97316",
    label: "PyS",
    symbol: `<path d="m86 66 18 40 44-8-30 34 22 44-42-20-32 34 4-46-42-20 46-10 12-48Z" fill="#f97316"/><path d="M146 82c30 8 50 25 62 53M132 116c26 7 44 21 56 42" fill="none" stroke="#38bdf8" stroke-width="10" stroke-linecap="round"/><path d="M74 178c30 12 62 12 96 0" stroke="#facc15" stroke-width="12" stroke-linecap="round"/>`
  },
  "Storage Transfer Service": {
    accent: "#0ea5e9",
    label: "STS",
    symbol: `<path d="M54 92h70v78H54z" fill="#38bdf8"/><path d="M132 92h70v78h-70z" fill="#22c55e"/><path d="M111 131h34" stroke="#f59e0b" stroke-width="14" stroke-linecap="round"/><path d="m137 108 28 23-28 23" fill="none" stroke="#f59e0b" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/><path d="M72 72h34M150 190h34" stroke="#bfdbfe" stroke-width="12" stroke-linecap="round"/>`
  },
  "Cloud Cost Optimization": {
    accent: "#16a34a",
    label: "CCO",
    symbol: `<path d="M76 154h100c22 0 38-15 38-35 0-19-14-33-33-36-9-20-29-34-52-34-29 0-52 20-58 46-19 4-31 16-31 31 0 17 15 28 36 28Z" fill="#38bdf8"/><path d="M128 92v80M104 112c8-14 40-14 48 0M104 152c8 14 40 14 48 0" fill="none" stroke="#16a34a" stroke-width="12" stroke-linecap="round"/>`
  },
  "Financial Reconciliation": {
    accent: "#0f766e",
    label: "Recon",
    symbol: `<rect x="56" y="62" width="144" height="132" rx="18" fill="#0f766e"/><path d="M84 98h84M84 130h54M84 162h84" stroke="#ccfbf1" stroke-width="12" stroke-linecap="round"/><path d="m156 128 20 20 34-48" fill="none" stroke="#f59e0b" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  "SAP Acknowledgements": {
    accent: "#0284c7",
    label: "Ack",
    symbol: `<path d="M52 78h152l-28 96H52V78Z" fill="#0284c7"/><text x="128" y="122" text-anchor="middle" dominant-baseline="middle" font-family="Arial, Helvetica, sans-serif" font-size="42" font-weight="900" fill="#ffffff">SAP</text><path d="m88 184 24 24 54-62" fill="none" stroke="#22c55e" stroke-width="14" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  "LLM / RAG": {
    accent: "#a855f7",
    label: "AI",
    symbol: `<path d="M88 86c0-24 18-42 42-42s42 18 42 42v76c0 24-18 42-42 42s-42-18-42-42V86Z" fill="#a855f7"/><path d="M88 112H60M88 148H60M172 112h24M172 148h24M112 78h32M112 178h32" stroke="#c4b5fd" stroke-width="12" stroke-linecap="round"/><circle cx="130" cy="128" r="22" fill="#f59e0b"/>`
  },
  "Vector DB": {
    accent: "#14b8a6",
    label: "VDB",
    symbol: `<circle cx="74" cy="76" r="18" fill="#14b8a6"/><circle cx="178" cy="76" r="18" fill="#38bdf8"/><circle cx="92" cy="176" r="18" fill="#f59e0b"/><circle cx="188" cy="166" r="18" fill="#a78bfa"/><path d="M90 78h72M80 94l10 66M174 92l12 58M106 174h66" stroke="#ccfbf1" stroke-width="10" stroke-linecap="round"/>`
  },
  "Graph DB": {
    accent: "#f43f5e",
    label: "GDB",
    symbol: `<circle cx="128" cy="74" r="20" fill="#f43f5e"/><circle cx="78" cy="150" r="20" fill="#38bdf8"/><circle cx="178" cy="150" r="20" fill="#22c55e"/><circle cx="128" cy="194" r="16" fill="#f59e0b"/><path d="M118 91 88 133M138 91l30 42M98 150h60M92 164l24 20M164 164l-24 20" stroke="#fecdd3" stroke-width="10" stroke-linecap="round"/>`
  },
  "ZIO": {
    accent: "#7c3aed",
    label: "ZIO",
    symbol: `<path d="M74 72h108l-74 112h74" fill="none" stroke="#7c3aed" stroke-width="22" stroke-linecap="round" stroke-linejoin="round"/><path d="M76 184h106" stroke="#22d3ee" stroke-width="12" stroke-linecap="round"/><circle cx="128" cy="128" r="18" fill="#f59e0b"/>`
  },
  "Akka": {
    accent: "#0f766e",
    label: "Ak",
    symbol: `<path d="M62 174 128 54l66 120h-38l-28-54-28 54H62Z" fill="#0f766e"/><path d="M112 148h32M100 174h56" stroke="#99f6e4" stroke-width="12" stroke-linecap="round"/>`
  },
  "Apache Camel": {
    accent: "#c2410c",
    label: "Cam",
    symbol: `<path d="M54 154c20-48 48-68 84-60 22 5 40 20 64 52" fill="none" stroke="#c2410c" stroke-width="22" stroke-linecap="round"/><path d="M78 158h108M90 178h78" stroke="#fb923c" stroke-width="14" stroke-linecap="round"/><circle cx="190" cy="120" r="12" fill="#f59e0b"/>`
  },
  "SAP": {
    accent: "#0ea5e9",
    label: "SAP",
    symbol: `<path d="M52 78h152l-28 100H52V78Z" fill="#0ea5e9"/><text x="128" y="136" text-anchor="middle" dominant-baseline="middle" font-family="Arial, Helvetica, sans-serif" font-size="50" font-weight="900" fill="#ffffff">SAP</text>`
  },
  "Chrome Extensions": {
    accent: "#facc15",
    label: "CE",
    symbol: `<circle cx="128" cy="128" r="70" fill="#facc15"/><path d="M128 58a70 70 0 0 1 61 36h-72" fill="#ef4444"/><path d="M189 94a70 70 0 0 1-61 104l36-62" fill="#22c55e"/><path d="M128 198A70 70 0 0 1 67 94l36 62" fill="#3b82f6"/><circle cx="128" cy="128" r="28" fill="#f8fafc"/><path d="M128 108v40M108 128h40" stroke="#0f172a" stroke-width="10" stroke-linecap="round"/>`
  },
  "ScalaTest": {
    accent: "#22c55e",
    label: "ST",
    symbol: `<path d="M128 46 198 76v52c0 44-28 76-70 92-42-16-70-48-70-92V76l70-30Z" fill="#22c55e"/><path d="m92 132 26 26 50-62" fill="none" stroke="#dcfce7" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  "Mockito": {
    accent: "#7c3aed",
    label: "Mo",
    symbol: `<rect x="64" y="68" width="128" height="120" rx="22" fill="#7c3aed"/><circle cx="104" cy="114" r="15" fill="#f8fafc"/><circle cx="152" cy="114" r="15" fill="#f8fafc"/><path d="M100 154c18 14 38 14 56 0" fill="none" stroke="#ddd6fe" stroke-width="12" stroke-linecap="round"/><path d="M88 54h80" stroke="#f59e0b" stroke-width="12" stroke-linecap="round"/>`
  },
  "Integration Testing": {
    accent: "#06b6d4",
    label: "IT",
    symbol: `<rect x="58" y="72" width="58" height="58" rx="14" fill="#06b6d4"/><rect x="140" y="126" width="58" height="58" rx="14" fill="#22c55e"/><path d="M116 102h22c18 0 28 10 28 28" fill="none" stroke="#f59e0b" stroke-width="14" stroke-linecap="round"/><path d="m150 112 20 20-20 20" fill="none" stroke="#f59e0b" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>`
  },
  "CI/CD": {
    accent: "#2563eb",
    label: "CI",
    symbol: `<path d="M62 128h36M158 128h36" stroke="#2563eb" stroke-width="18" stroke-linecap="round"/><circle cx="128" cy="128" r="36" fill="none" stroke="#60a5fa" stroke-width="14"/><path d="m128 82 18 18-18 18M128 174l-18-18 18-18" fill="none" stroke="#f59e0b" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/>`
  }
};

const defaultSkillLogo = {
  accent: "#087f8c",
  label: "Dev",
  symbol: `<path d="M84 78 44 128l40 50" fill="none" stroke="#38bdf8" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/><path d="m172 78 40 50-40 50" fill="none" stroke="#4ade80" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/><path d="m144 62-32 132" stroke="#f59e0b" stroke-width="16" stroke-linecap="round"/>`
};

const getSkillLogo = (technology) => {
  const logo = skillLogoSymbols[technology.name] || defaultSkillLogo;
  return {
    ...logo,
    label: technology.short || logo.label || technology.name.slice(0, 3),
  };
};

// ::: Code Generated by Copilot [c31fca73-07ad-497d-b61a-e0717eda8181]. This comment will be removed automatically after the file is saved :::
const drawRoundedRect = (context, left, top, width, height, radius) => {
  context.beginPath();
  context.moveTo(left + radius, top);
  context.lineTo(left + width - radius, top);
  context.quadraticCurveTo(left + width, top, left + width, top + radius);
  context.lineTo(left + width, top + height - radius);
  context.quadraticCurveTo(left + width, top + height, left + width - radius, top + height);
  context.lineTo(left + radius, top + height);
  context.quadraticCurveTo(left, top + height, left, top + height - radius);
  context.lineTo(left, top + radius);
  context.quadraticCurveTo(left, top, left + radius, top);
  context.closePath();
};

const createSkillTexture = ({ accent, label }) => {
  const canvas = document.createElement("canvas");
  canvas.width = 256;
  canvas.height = 256;

  const context = canvas.getContext("2d");
  const normalizedLabel = String(label || "Dev").replace(/\s+/g, "").slice(0, 5);
  const textSize = normalizedLabel.length > 4 ? 42 : normalizedLabel.length > 3 ? 48 : 58;
  const logoColor = accent || "#087f8c";

  context.clearRect(0, 0, 256, 256);
  context.fillStyle = logoColor;
  context.globalAlpha = 0.92;
  drawRoundedRect(context, 74, 74, 108, 108, 32);
  context.fill();

  context.globalAlpha = 0.28;
  context.strokeStyle = "#ffffff";
  context.lineWidth = 13;
  context.beginPath();
  context.arc(128, 128, 68, Math.PI * 0.12, Math.PI * 1.7);
  context.stroke();

  context.globalAlpha = 1;
  context.fillStyle = "#ffffff";
  context.font = `900 ${textSize}px Arial, Helvetica, sans-serif`;
  context.textAlign = "center";
  context.textBaseline = "middle";
  context.shadowColor = "rgba(15, 23, 42, 0.38)";
  context.shadowBlur = 10;
  context.fillText(normalizedLabel, 128, 132);
  context.shadowBlur = 0;

  const texture = new THREE.CanvasTexture(canvas);
  texture.minFilter = THREE.LinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.needsUpdate = true;

  return texture;
};

const SkillBallsCanvas = ({ skills }) => {
  const layerRef = useRef(null);
  const canvasRef = useRef(null);

  // ::: Code Generated by Copilot [c31fca73-07ad-497d-b61a-e0717eda8181]. This comment will be removed automatically after the file is saved :::
  useEffect(() => {
    const layer = layerRef.current;
    const canvas = canvasRef.current;
    if (!layer || !canvas) {
      return undefined;
    }

    const renderer = new THREE.WebGLRenderer({
      canvas,
      alpha: true,
      antialias: true,
      powerPreference: "low-power",
    });
    const scene = new THREE.Scene();
    const camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0.1, 1000);
    const pixelRatio = Math.min(window.devicePixelRatio || 1, 1.5);
    const sphereGeometry = new THREE.IcosahedronGeometry(38, 1);
    const labelGeometry = new THREE.PlaneGeometry(52, 52);

    camera.position.set(0, 0, 240);
    renderer.setClearColor(0x000000, 0);
    renderer.setPixelRatio(pixelRatio);
    if (THREE.SRGBColorSpace) {
      renderer.outputColorSpace = THREE.SRGBColorSpace;
    }

    scene.add(new THREE.AmbientLight(0xffffff, 0.68));
    const keyLight = new THREE.DirectionalLight(0xffffff, 1.18);
    keyLight.position.set(120, 140, 180);
    scene.add(keyLight);
    const accentLight = new THREE.PointLight(0x4fd1c5, 0.45);
    accentLight.position.set(-180, -80, 140);
    scene.add(accentLight);

    const ballObjects = skills.map((skill, index) => {
      const accentColor = new THREE.Color(skill.logo.accent || "#087f8c");
      const sphereMaterial = new THREE.MeshStandardMaterial({
        color: 0xfff8eb,
        emissive: accentColor,
        emissiveIntensity: 0.07,
        roughness: 0.48,
        metalness: 0.08,
        flatShading: true,
        polygonOffset: true,
        polygonOffsetFactor: -5,
      });
      const sphere = new THREE.Mesh(sphereGeometry, sphereMaterial);
      const labelTexture = createSkillTexture(skill.logo);
      const labelMaterial = new THREE.MeshBasicMaterial({
        map: labelTexture,
        transparent: true,
        depthTest: false,
        depthWrite: false,
      });
      const labelMesh = new THREE.Mesh(labelGeometry, labelMaterial);
      labelMesh.renderOrder = 4;
      scene.add(sphere);
      scene.add(labelMesh);

      return {
        key: skill.technology.name,
        sphere,
        sphereMaterial,
        labelMesh,
        labelMaterial,
        labelTexture,
        baseHorizontalPosition: 0,
        baseVerticalPosition: 0,
        phase: index * 0.37,
      };
    });

    // ::: Code Generated by Copilot [d965c69a-3945-4493-b174-2a1ffae5f8af]. This comment will be removed automatically after the file is saved :::
    let animationFrameId = 0;
    let resizeObserver;

    const updateLayout = () => {
      const grid = layer?.parentElement;
      if (!grid) {
        return;
      }

      const gridRect = grid.getBoundingClientRect();
      const skillCards = Array.from(grid.querySelectorAll(".Skill"));
      if (gridRect.width <= 0 || gridRect.height <= 0) {
        return;
      }

      renderer.setSize(gridRect.width, gridRect.height, false);
      camera.left = -gridRect.width / 2;
      camera.right = gridRect.width / 2;
      camera.top = gridRect.height / 2;
      camera.bottom = -gridRect.height / 2;
      camera.updateProjectionMatrix();

      ballObjects.forEach((ballObject, index) => {
        const skillCard = skillCards[index];
        const visual = skillCard.querySelector(".SkillVisual");
        if (!visual) {
          ballObject.sphere.visible = false;
          ballObject.labelMesh.visible = false;
          return;
        }

        const visualRect = visual.getBoundingClientRect();
        const visualHorizontalCenter = visualRect.left - gridRect.left + visualRect.width / 2;
        const visualVerticalCenter = visualRect.top - gridRect.top + visualRect.height / 2;
        ballObject.baseHorizontalPosition = visualHorizontalCenter - gridRect.width / 2;
        ballObject.baseVerticalPosition = gridRect.height / 2 - visualVerticalCenter;
        ballObject.sphere.visible = true;
        ballObject.labelMesh.visible = true;
      });
    };

    const scheduleUpdate = () => {
      // ::: Code Generated by Copilot [d965c69a-3945-4493-b174-2a1ffae5f8af]. This comment will be removed automatically after the file is saved :::
      updateLayout();
    };

    const animate = (timestamp) => {
      const elapsedSeconds = timestamp / 1000;
      ballObjects.forEach((ballObject) => {
        const floatOffset = Math.sin(elapsedSeconds * 1.1 + ballObject.phase) * 3.5;
        ballObject.sphere.position.set(ballObject.baseHorizontalPosition, ballObject.baseVerticalPosition + floatOffset, 0);
        ballObject.labelMesh.position.set(ballObject.baseHorizontalPosition, ballObject.baseVerticalPosition + floatOffset, 43);
        ballObject.sphere.rotation.x = elapsedSeconds * 0.28 + ballObject.phase * 0.2;
        ballObject.sphere.rotation.y = elapsedSeconds * 0.42 + ballObject.phase;
      });
      renderer.render(scene, camera);
      animationFrameId = window.requestAnimationFrame(animate);
    };

    scheduleUpdate();
    animate(0);
    const lateLayoutTimer = window.setTimeout(scheduleUpdate, 500);
    const layoutRetryTimer = window.setInterval(scheduleUpdate, 300);

    if (window.ResizeObserver && layerRef.current?.parentElement) {
      resizeObserver = new ResizeObserver(scheduleUpdate);
      resizeObserver.observe(layerRef.current.parentElement);
      Array.from(layerRef.current.parentElement.querySelectorAll(".Skill")).forEach((skillCard) => resizeObserver.observe(skillCard));
    }

    window.addEventListener("resize", scheduleUpdate);
    window.addEventListener("scroll", scheduleUpdate, { passive: true });

    return () => {
      window.cancelAnimationFrame(animationFrameId);
      window.clearTimeout(lateLayoutTimer);
      window.clearInterval(layoutRetryTimer);
      resizeObserver?.disconnect();
      window.removeEventListener("resize", scheduleUpdate);
      window.removeEventListener("scroll", scheduleUpdate);
      ballObjects.forEach((ballObject) => {
        scene.remove(ballObject.sphere);
        scene.remove(ballObject.labelMesh);
        ballObject.sphereMaterial.dispose();
        ballObject.labelMaterial.dispose();
        ballObject.labelTexture.dispose();
      });
      sphereGeometry.dispose();
      labelGeometry.dispose();
      renderer.dispose();
    };
  }, [skills]);

  return (
    <div className="SkillBallsLayer" ref={layerRef} aria-hidden="true">
      {/* ::: Code Generated by Copilot [c31fca73-07ad-497d-b61a-e0717eda8181]. This comment will be removed automatically after the file is saved ::: */}
      <canvas className="SkillBallsCanvasElement" ref={canvasRef} />
    </div>
  );
};

// ::: Code Generated by Copilot [02538a2b-1479-4df0-aacf-28679cc6e6e4]. This comment will be removed automatically after the file is saved :::
const SkillCard = ({ technology, logo }) => {
  // ::: Code Generated by Copilot [5b10cb95-02fa-4445-bf2f-5c2fd86ff281]. This comment will be removed automatically after the file is saved :::
  return (
    <article className="Skill" data-skill-name={technology.name} style={{ "--skill-accent": logo.accent }}>
      <div className="SkillVisual">
        {/* ::: Code Generated by Copilot [5b10cb95-02fa-4445-bf2f-5c2fd86ff281]. This comment will be removed automatically after the file is saved ::: */}
        {/* ::: Code Generated by Copilot [7d16f9e2-79ff-42e9-a09e-c552d45f7253]. This comment will be removed automatically after the file is saved ::: */}
        {/* ::: Code Generated by Copilot [c566fe53-3e11-4694-8503-b2389cbad6ac]. This comment will be removed automatically after the file is saved ::: */}
        {/* ::: Code Generated by Copilot [f516326b-dd21-4f05-81a6-ff25510cc74f]. This comment will be removed automatically after the file is saved ::: */}
        <div className="SkillIconPreview SkillIconFallback" aria-hidden="true"><span>{logo.label}</span></div>
      </div>
      <div className="SkillTextBox">
        <span>{technology.name}</span>
        <small>{technology.category}</small>
      </div>
    </article>
  );
};

function Skills() {
  // ::: Code Generated by Copilot [f516326b-dd21-4f05-81a6-ff25510cc74f]. This comment will be removed automatically after the file is saved :::
  const skillViews = useMemo(() => technologies.map((technology) => ({
    technology,
    logo: getSkillLogo(technology),
  })), []);

  return (
    <div className="mainSkill" id="Skills">
        <motion.div variants={textVariant()}>
            <p className="AboutH2">Technologies I work with</p>
            <h2 className="AboutH1">Skills.</h2>
        </motion.div>
        <div className="Skills">
          {/* ::: Code Generated by Copilot [f516326b-dd21-4f05-81a6-ff25510cc74f]. This comment will be removed automatically after the file is saved ::: */}
          <SkillBallsCanvas skills={skillViews} />
          {skillViews.map(({ technology, logo }) => (
            <SkillCard technology={technology} logo={logo} key={technology.name} />
          ))}
        </div>
    </div>
  )
}

export default SectionWrapper(Skills,"skills");