// ::: Code Generated by Copilot [7d16f9e2-79ff-42e9-a09e-c552d45f7253]. This comment will be removed automatically after the file is saved :::
import React, { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import {
  Float,
  OrbitControls,
} from "@react-three/drei";

import CanvasLoader from "../../Loader/Loader.js";

// ::: Code Generated by Copilot [7d16f9e2-79ff-42e9-a09e-c552d45f7253]. This comment will be removed automatically after the file is saved :::
const Ball = ({ accent = "#087f8c" }) => {
  return (
    // ::: Code Generated by Copilot [a78696f7-4f3a-457f-b814-dd3df4038ab2]. This comment will be removed automatically after the file is saved :::
    <Float speed={1.1} rotationIntensity={0.65} floatIntensity={1.1}>
      {/* ::: Code Generated by Copilot [7af934ba-8d81-4f9c-a180-9d565f0a5211]. This comment will be removed automatically after the file is saved ::: */}
      <mesh scale={1.28}>
        <icosahedronGeometry args={[1, 2]} />
        <meshBasicMaterial color={accent} wireframe={false} />
      </mesh>
    </Float>
  );
};

const BallCanvas = ({ accent }) => {
  return (
    <Canvas
      dpr={[1, 2]}
      camera={{ position: [0, 0, 5], fov: 45 }}
      gl={{ preserveDrawingBuffer: false, antialias: true, powerPreference: "low-power" }}
    >
      {/* ::: Code Generated by Copilot [7af934ba-8d81-4f9c-a180-9d565f0a5211]. This comment will be removed automatically after the file is saved ::: */}
      <ambientLight intensity={0.75} />
      <directionalLight position={[3, 3, 5]} intensity={1.2} />
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls enableZoom={false} />
        <Ball accent={accent} />
      </Suspense>
    </Canvas>
  );
};

export default BallCanvas;