// ::: Code Generated by Copilot [752456af-79bb-4078-bdd5-898f863c31c9]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [864625c6-e04f-4895-860d-1ac51f4b0a47]. This comment will be removed automatically after the file is saved :::
// ::: Code Generated by Copilot [af39c291-6c37-47e2-a7ad-b31644a81e0d]. This comment will be removed automatically after the file is saved :::
import React, { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Preload, useGLTF } from "@react-three/drei";

import CanvasLoader from "../../Loader/Loader.js";

const planetModelPath = `${process.env.PUBLIC_URL || ""}/planet/scene.gltf`;

const Earth = () => {
  // ::: Code Generated by Copilot [af39c291-6c37-47e2-a7ad-b31644a81e0d]. This comment will be removed automatically after the file is saved :::
  const earth = useGLTF(planetModelPath);

  return (
    <primitive object={earth.scene} scale={2.5} position-y={0} rotation-y={0} />
  );
};

const EarthCanvas = () => {
  return (
    <Canvas
      shadows
      frameloop='always'
      dpr={[1, 2]}
      gl={{ preserveDrawingBuffer: true }}
      camera={{
        fov: 45,
        near: 0.1,
        far: 200,
        position: [-4, 3, 6],
      }}
    >
      <Suspense fallback={<CanvasLoader />}>
        {/* ::: Code Generated by Copilot [af39c291-6c37-47e2-a7ad-b31644a81e0d]. This comment will be removed automatically after the file is saved ::: */}
        <OrbitControls
          autoRotate
          autoRotateSpeed={1.4}
          enableZoom={false}
          maxPolarAngle={Math.PI / 2}
          minPolarAngle={Math.PI / 2}
        />
        <Earth />

        <Preload all />
      </Suspense>
    </Canvas>
  );
};

useGLTF.preload(planetModelPath);

export default EarthCanvas;