// ::: Code Generated by Copilot [9b77e7f9-3d5b-4a06-9f58-3a5db4c5f0fb]. This comment will be removed automatically after the file is saved :::
import './App.css';
import React, { useEffect, useState } from "react";
import Home from "./Pages/Home/Home.js";
import Navbar from './Components/Navbar/Navbar.js';
import About from "./Pages/About/About.js";
import Education from './Pages/Education/Education.js';
import Skills from './Pages/Skills/Skills.js';
import Projects from './Pages/Projects/Projects.js';
// ::: Code Generated by Copilot [5728d601-8dd4-4305-bd51-3109b120768d]. This comment will be removed automatically after the file is saved :::
import Campus from './Pages/Campus/Campus.js';
import Contact from './Pages/Contact/Contact.js';
import StarsCanvas from './Components/canvas/Stars.js';
import CustomCursor from "./CustomCursor";
import Loader from "./Loader/index.js";

import WorkExperience from "./Pages/Experience/Experience.js"
import { BrowserRouter as Router } from "react-router-dom";

function App() {
  const [preLoader, setPreLoader] = useState(true);

  // ::: Code Generated by Copilot [9b77e7f9-3d5b-4a06-9f58-3a5db4c5f0fb]. This comment will be removed automatically after the file is saved :::
  useEffect(() => {
    const loaderTimer = setTimeout(() => {
      setPreLoader(false);
    }, 1200);

    return () => clearTimeout(loaderTimer);
  }, []);

  return (
    <>
    <CustomCursor down={false} />
    {preLoader ? <Loader msg = "Loading..." /> :
      <Router >
      <div className="App">
      <Navbar />
        <Home />
        <About />
        {/* ::: Code Generated by Copilot [ef1d33c2-0bb7-4644-a13d-c2bc0ac580b2]. This comment will be removed automatically after the file is saved ::: */}
        <WorkExperience />
        <div className="starsCanvas">
          <Skills />
          <StarsCanvas />
        </div>
        <Projects />    
        <Education />
        <Campus />
        <div className="starsCanvas">
          <Contact />
          <StarsCanvas />
        </div>
      </div>
    </Router>   
    }
    </>
    
  );
}

export default App;
